spring.application.name=demo
server.port=8081

#spring.datasource.url=jdbc:mysql://localhost:3307/vista
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3307/vistadb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false